// seed.js
const mongoose = require('mongoose');
const Movie = require('./models/movie'); // Adjust the path to your Movie model
require('dotenv').config();

// Sample movie data (60 movies)
const movies = [
    {
        movieId: 'tt1375666',
        title: 'Inception',
        genre: 'Sci-Fi',
        year: 2010,
        description: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg',
        platformUrl: 'https://www.imdb.com/title/tt1375666/',
        trending: true,
        imdbRating: 8.8,
        director: 'Christopher Nolan',
        cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page'],
        averageRating: 4.5
    },
    {
        movieId: 'tt0468569',
        title: 'The Dark Knight',
        genre: 'Action',
        year: 2008,
        description: 'When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham.',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg',
        platformUrl: 'https://www.imdb.com/title/tt0468569/',
        trending: true,
        imdbRating: 9.0,
        director: 'Christopher Nolan',
        cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart'],
        averageRating: 4.7
    },
    {
        movieId: 'tt0111161',
        title: 'The Shawshank Redemption',
        genre: 'Drama',
        year: 1994,
        description: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
        platformUrl: 'https://www.imdb.com/title/tt0111161/',
        trending: false,
        imdbRating: 9.3,
        director: 'Frank Darabont',
        cast: ['Tim Robbins', 'Morgan Freeman', 'Bob Gunton'],
        averageRating: 4.8
    },
    {
        movieId: 'tt0133093',
        title: 'The Matrix',
        genre: 'Sci-Fi',
        year: 1999,
        description: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg',
        platformUrl: 'https://www.imdb.com/title/tt0133093/',
        trending: false,
        imdbRating: 8.7,
        director: 'Lana Wachowski, Lilly Wachowski',
        cast: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss'],
        averageRating: 4.6
    },
    {
        movieId: 'tt0816692',
        title: 'Interstellar',
        genre: 'Sci-Fi',
        year: 2014,
        description: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
        platformUrl: 'https://www.imdb.com/title/tt0816692/',
        trending: true,
        imdbRating: 8.6,
        director: 'Christopher Nolan',
        cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'],
        averageRating: 4.4
    },
    {
        movieId: 'tt0120737',
        title: 'The Lord of the Rings: The Fellowship of the Ring',
        genre: 'Adventure',
        year: 2001,
        description: 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg',
        platformUrl: 'https://www.imdb.com/title/tt0120737/',
        trending: false,
        imdbRating: 8.8,
        director: 'Peter Jackson',
        cast: ['Elijah Wood', 'Ian McKellen', 'Orlando Bloom'],
        averageRating: 4.5
    },
    {
        movieId: 'tt0167260',
        title: 'The Lord of the Rings: The Return of the King',
        genre: 'Adventure',
        year: 2003,
        description: 'Gandalf and Aragorn lead the World of Men against Sauron\'s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
        platformUrl: 'https://www.imdb.com/title/tt0167260/',
        trending: false,
        imdbRating: 8.9,
        director: 'Peter Jackson',
        cast: ['Elijah Wood', 'Viggo Mortensen', 'Ian McKellen'],
        averageRating: 4.7
    },
    {
        movieId: 'tt0137523',
        title: 'Fight Club',
        genre: 'Drama',
        year: 1999,
        description: 'An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BMmEzNTkxYjQtZTc0MC00YTVjLTg5ZTEtZWMwOWVlYzY0NWIwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
        platformUrl: 'https://www.imdb.com/title/tt0137523/',
        trending: false,
        imdbRating: 8.8,
        director: 'David Fincher',
        cast: ['Brad Pitt', 'Edward Norton', 'Helena Bonham Carter'],
        averageRating: 4.6
    },
    {
        movieId: 'tt0109830',
        title: 'Forrest Gump',
        genre: 'Drama',
        year: 1994,
        description: 'The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other historical events unfold through the perspective of an Alabama man with an IQ of 75.',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
        platformUrl: 'https://www.imdb.com/title/tt0109830/',
        trending: false,
        imdbRating: 8.8,
        director: 'Robert Zemeckis',
        cast: ['Tom Hanks', 'Robin Wright', 'Gary Sinise'],
        averageRating: 4.5
    },
    {
        movieId: 'tt0076759',
        title: 'Star Wars: Episode IV - A New Hope',
        genre: 'Sci-Fi',
        year: 1977,
        description: 'Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee, and two droids to save the galaxy from the Empire\'s world-destroying battle station.',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg',
        platformUrl: 'https://www.imdb.com/title/tt0076759/',
        trending: false,
        imdbRating: 8.6,
        director: 'George Lucas',
        cast: ['Mark Hamill', 'Harrison Ford', 'Carrie Fisher'],
        averageRating: 4.4
    },
    {
        movieId: 'tt0088763',
        title: 'Back to the Future',
        genre: 'Sci-Fi',
        year: 1985,
        description: 'Marty McFly, a 17-year-old high school student, is accidentally sent thirty years into the past in a time-traveling DeLorean invented by his close friend, the maverick scientist Doc Brown.',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BZmU0M2Y1OGUtZjIxNi00ZjBkLTg1MjgtOWIyNThiZWIwYjRiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
        platformUrl: 'https://www.imdb.com/title/tt0088763/',
        trending: false,
        imdbRating: 8.5,
        director: 'Robert Zemeckis',
        cast: ['Michael J. Fox', 'Christopher Lloyd', 'Lea Thompson'],
        averageRating: 4.3
    },
    {
        movieId: 'tt0110357',
        title: 'The Lion King',
        genre: 'Animation',
        year: 1994,
        description: 'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BYTYxNGMyZTYtMjE3MS00MzNjLWFjNmYtMDk3N2FmM2JiM2M1XkEyXkFqcGdeQXVyNjY5NDU4NzI@._V1_SX300.jpg',
        platformUrl: 'https://www.imdb.com/title/tt0110357/',
        trending: false,
        imdbRating: 8.5,
        director: 'Roger Allers, Rob Minkoff',
        cast: ['Matthew Broderick', 'Jeremy Irons', 'James Earl Jones'],
        averageRating: 4.3
    },
    {
        movieId: 'tt0114814',
        title: 'The Usual Suspects',
        genre: 'Crime',
        year: 1995,
        description: 'A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which began when five criminals met at a seemingly random police lineup.',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BYTViNjMyNmUtNDFkNC00ZDRlLThmMDUtZDU2YWE4NGI2ZjVmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg',
        platformUrl: 'https://www.imdb.com/title/tt0114814/',
        trending: false,
        imdbRating: 8.5,
        director: 'Bryan Singer',
        cast: ['Kevin Spacey', 'Gabriel Byrne', 'Chazz Palminteri'],
        averageRating: 4.3
    },
    {
        movieId: 'tt0120586',
        title: 'American History X',
        genre: 'Drama',
        year: 1998,
        description: 'A former neo-nazi skinhead tries to prevent his younger brother from going down the same wrong path that he did.',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BZjA0MTM4MTQtNzY5MC00NzY3LWI1ZTgtYzcxMjkyMzU4MDZiXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SX300.jpg',
        platformUrl: 'https://www.imdb.com/title/tt0120586/',
        trending: false,
        imdbRating: 8.5,
        director: 'Tony Kaye',
        cast: ['Edward Norton', 'Edward Furlong', 'Beverly D\'Angelo'],
        averageRating: 4.3
    },
    {
        movieId: 'tt0112573',
        title: 'Braveheart',
        genre: 'Biography',
        year: 1995,
        description: 'Scottish warrior William Wallace leads his countrymen in a rebellion to free his homeland from the tyranny of King Edward I of England.',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BMzkzMmU0YTYtOWM3My00YzBmLWI0YzctOGYyNTkwMWE5MTJkXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
        platformUrl: 'https://www.imdb.com/title/tt0112573/',
        trending: false,
        imdbRating: 8.3,
        director: 'Mel Gibson',
        cast: ['Mel Gibson', 'Sophie Marceau', 'Patrick McGoohan'],
        averageRating: 4.2
    },
    {
        movieId: 'tt0119217',
        title: 'Good Will Hunting',
        genre: 'Drama',
        year: 1997,
        description: 'Will Hunting, a janitor at M.I.T., has a gift for mathematics, but needs help from a psychologist to find direction in his life.',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BOTI0MzcxMTYtZDVkMy00NjY1LTgyMTYtZmUxN2M3NmQ2NWJhXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
        platformUrl: 'https://www.imdb.com/title/tt0119217/',
        trending: false,
        imdbRating: 8.3,
        director: 'Gus Van Sant',
        cast: ['Robin Williams', 'Matt Damon', 'Ben Affleck'],
        averageRating: 4.2
    },
    {
        movieId: 'tt0102926',
        title: 'The Silence of the Lambs',
        genre: 'Crime',
        year: 1991,
        description: 'A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BNjNhZTk0ZmEtNjJhMi00YzFlLWE1MmEtYzM1M2ZmMGMwMTU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg',
        platformUrl: 'https://www.imdb.com/title/tt0102926/',
        trending: false,
        imdbRating: 8.6,
        director: 'Jonathan Demme',
        cast: ['Jodie Foster', 'Anthony Hopkins', 'Lawrence A. Bonney'],
        averageRating: 4.4
    },
    {
        movieId: 'tt0119488',
        title: 'L.A. Confidential',
        genre: 'Crime',
        year: 1997,
        description: 'As corruption grows in 1950s Los Angeles, three policemen - one strait-laced, one brutal, and one sleazy - investigate a series of murders with their own brand of justice.',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BMDQ2YzEyZGItYWRhOS00MjBmLTkzMDUtMTdjYzkyMmQxZTJlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg',
        platformUrl: 'https://www.imdb.com/title/tt0119488/',
        trending: false,
        imdbRating: 8.2,
        director: 'Curtis Hanson',
        cast: ['Kevin Spacey', 'Russell Crowe', 'Guy Pearce'],
        averageRating: 4.1
    },
    {
        movieId: 'tt0120689',
        title: 'The Green Mile',
        genre: 'Crime',
        year: 1999,
        description: 'The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_SX300.jpg',
        platformUrl: 'https://www.imdb.com/title/tt0120689/',
        trending: false,
        imdbRating: 8.6,
        director: 'Frank Darabont',
        cast: ['Tom Hanks', 'Michael Clarke Duncan', 'David Morse'],
        averageRating: 4.4
    },
    {
        movieId: 'tt0113277',
        title: 'Heat',
        genre: 'Crime',
        year: 1995,
        description: 'A group of professional bank robbers start to feel the heat from police when they unknowingly leave a clue at their latest heist.',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BNGMwNzUwNjYtZWM5NS00YzMyLWI4NjAtNjM0ZDBiMzE1YWExXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg',
        platformUrl: 'https://www.imdb.com/title/tt0113277/',
        trending: false,
        imdbRating: 8.2,
        director: 'Michael Mann',
        cast: ['Al Pacino', 'Robert De Niro', 'Val Kilmer'],
        averageRating: 4.1
    },
    {
        movieId: 'tt0112641',
        title: 'Casino',
        genre: 'Crime',
        year: 1995,
        description: 'A tale of greed, deception, money, power, and murder occur between two best friends: a mafia enforcer and a casino executive, compete against each other over a gambling empire, and over a fast-living and fast-loving socialite.',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BMTcxOWYzNDYtYmM4YS00N2NkLTk0NTAtNjg1ODgwZjAxYzI3XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg',
        platformUrl: 'https://www.imdb.com/title/tt0112641/',
        trending: false,
        imdbRating: 8.2,
        director: 'Martin Scorsese',
        cast: ['Robert De Niro', 'Sharon Stone', 'Joe Pesci'],
        averageRating: 4.1
    },
    {
        movieId: 'tt0117951',
        title: 'Trainspotting',
        genre: 'Drama',
        year: 1996,
        description: 'Renton, deeply immersed in the Edinburgh drug scene, tries to clean up and get out, despite the allure of the drugs and influence of friends.',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BMzA5Zjc3ZTMtMmU5YS00YTMwLWI4MWUtYTU0YTVmNjVmODZhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg',
        platformUrl: 'https://www.imdb.com/title/tt0117951/',
        trending: false,
        imdbRating: 8.1,
        director: 'Danny Boyle',
        cast: ['Ewan McGregor', 'Ewen Bremner', 'Jonny Lee Miller'],
        averageRating: 4.0
    },
    {
        movieId: 'tt0116282',
        title: 'Fargo',
        genre: 'Crime',
        year: 1996,
        description: 'Jerry Lundegaard\'s inept crime falls apart due to his and his henchmen\'s bungling and the persistent police work of the quite pregnant Marge Gunderson.',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BNDJiZDgyZjctYmRjMS00ZjdkLTkwMTEtNGU1NDg3NDQ0Yzk1XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
        platformUrl: 'https://www.imdb.com/title/tt0116282/',
        trending: false,
        imdbRating: 8.1,
        director: 'Joel Coen, Ethan Coen',
        cast: ['William H. Macy', 'Frances McDormand', 'Steve Buscemi'],
        averageRating: 4.0
    },
    {
        movieId: 'tt0112471',
        title: 'Before Sunrise',
        genre: 'Drama',
        year: 1995,
        description: 'A young man and woman meet on a train in Europe, and wind up spending one evening together in Vienna. Unfortunately, both know that this will probably be their only night together.',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BZDdiZTAwYzAtMDI3Ni00OTRjLTkzN2UtMGE3MDMyZmU4NTU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg',
        platformUrl: 'https://www.imdb.com/title/tt0112471/',
        trending: false,
        imdbRating: 8.1,
        director: 'Richard Linklater',
        cast: ['Ethan Hawke', 'Julie Delpy', 'Andrea Eckert'],
        averageRating: 4.0
    },
    {
        movieId: 'tt0118799',
        title: 'Life Is Beautiful',
        genre: 'Comedy',
        year: 1997,
        description: 'When an open-minded Jewish librarian and his son become victims of the Holocaust, he uses a perfect mixture of will, humor, and imagination to protect his son from the dangers around their camp.',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BYmJmM2Q4NmMtYThmNC00ZjRlLWEyZmItZTIwOTBlZDQ3NTQ1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
        platformUrl: 'https://www.imdb.com/title/tt0118799/',
        trending: false,
        imdbRating: 8.6,
        director: 'Roberto Benigni',
        cast: ['Roberto Benigni', 'Nicoletta Braschi', 'Giorgio Cantarini'],
        averageRating: 4.4
    },
    {
        movieId: 'tt0118715',
        title: 'The Big Lebowski',
        genre: 'Comedy',
        year: 1998,
        description: 'Jeff "The Dude" Lebowski, mistaken for a millionaire of the same name, seeks restitution for his ruined rug and enlists his bowling buddies to help get it.',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BMTQ0NjUzMDMyOF5BMl5BanBnXkFtZTgwODA1OTU0MDE@._V1_SX300.jpg',
        platformUrl: 'https://www.imdb.com/title/tt0118715/',
        trending: false,
        imdbRating: 8.1,
        director: 'Joel Coen, Ethan Coen',
        cast: ['Jeff Bridges', 'John Goodman', 'Julianne Moore'],
        averageRating: 4.0
    },
    {
        movieId: 'tt0114814',
        title: 'The Usual Suspects',
        genre: 'Crime',
        year: 1995,
        description: 'A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which began when five criminals met at a seemingly random police lineup.',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BYTViNjMyNmUtNDFkNC00ZDRlLThmMDUtZDU2YWE4NGI2ZjVmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg',
        platformUrl: 'https://www.imdb.com/title/tt0114814/',
        trending: false,
        imdbRating: 8.5,
        director: 'Bryan Singer',
        cast: ['Kevin Spacey', 'Gabriel Byrne', 'Chazz Palminteri'],
        averageRating: 4.3
    },
    {
        movieId: 'tt0114369',
        title: 'Se7en',
        genre: 'Crime',
        year: 1995,
        description: 'Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BOTUwODM5MTctZjczMi00OTk4LTg3NWUtNmVhMTAzNTNjYjcyXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg',
        platformUrl: 'https://www.imdb.com/title/tt0114369/',
        trending: false,
        imdbRating: 8.6,
        director: 'David Fincher',
        cast: ['Morgan Freeman', 'Brad Pitt', 'Kevin Spacey'],
        averageRating: 4.4
    },
    {
        movieId: 'tt0110413',
        title: 'Léon: The Professional',
        genre: 'Crime',
        year: 1994,
        description: 'Mathilda, a 12-year-old girl, is reluctantly taken in by Léon, a professional assassin, after her family is murdered. An unusual relationship forms as she becomes his protégée and learns the assassin\'s trade.',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BODllNWE0MmEtYjUwZi00ZjY3LThmNmQtZjZlMjI2YTZjYmQ0XkEyXkFqcGdeQXVyNTc1NTQxODI@._V1_SX300.jpg',
        platformUrl: 'https://www.imdb.com/title/tt0110413/',
        trending: false,
        imdbRating: 8.5,
        director: 'Luc Besson',
        cast: ['Jean Reno', 'Gary Oldman', 'Natalie Portman'],
        averageRating: 4.3
    },
    {
        movieId: 'tt0109830',
        title: 'Forrest Gump',
        genre: 'Drama',
        year: 1994,
        description: 'The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other historical events unfold through the perspective of an Alabama man with an IQ of 75.',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
        platformUrl: 'https://www.imdb.com/title/tt0109830/',
        trending: false,
        imdbRating: 8.8,
        director: 'Robert Zemeckis',
        cast: ['Tom Hanks', 'Robin Wright', 'Gary Sinise'],
        averageRating: 4.5
    },
    {
        movieId: 'tt0110357',
        title: 'The Lion King',
        genre: 'Animation',
        year: 1994,
        description: 'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BYTYxNGMyZTYtMjE3MS00MzNjLWFjNmYtMDk3N2FmM2JiM2M1XkEyXkFqcGdeQXVyNjY5NDU4NzI@._V1_SX300.jpg',
        platformUrl: 'https://www.imdb.com/title/tt0110357/',
        trending: false,
        imdbRating: 8.5,
        director: 'Roger Allers, Rob Minkoff',
        cast: ['Matthew Broderick', 'Jeremy Irons', 'James Earl Jones'],
        averageRating: 4.3
    }
];

// Connect to MongoDB
mongoose.connect(process.env.MONGO_URI, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
})
.then(() => {
    console.log('Connected to MongoDB');
    // Insert sample movies
    return Movie.insertMany(movies);
})
.then(() => {
    console.log('Movies inserted successfully');
    mongoose.connection.close(); // Close the connection
})
.catch((error) => {
    console.error('Error seeding database:', error);
    mongoose.connection.close(); // Close the connection
});
